project:
  type: website
  output-dir: docs

website:
  title: "Home"
  twitter-card: true
  open-graph: true
  favicon: logo.jpeg
  site-url: "https://sanjuvi.github.io/Blog/"
  navbar:
    right:
      - about.qmd
format:
  html:
    theme: zephyr
    css: styles.css

