project:
  type: website
  output-dir: docs

website:
  title: "Posts"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Sanjuvi/
      - icon: twitter
        href: https://twitter.com/PySanjeevi/
format:
  html:
    theme: cyborg
    css: styles.css



